# Curated list of racial/ethnic slurs used to seed the chat filter.
# Deliberately narrower than a general profanity list: normal swearing is
# allowed through chat, only slurs targeting race/ethnicity are blocked.
# Lowercase, base forms -- better_profanity's matcher already normalizes
# case, spacing, and common leetspeak substitutions against this list.

RACIAL_SLURS = [
    "nigger",
    "nigga",
    "niggar",
    "niggard",
    "negro",
    "coon",
    "jigaboo",
    "spade",
    "sambo",
    "porch monkey",
    "spearchucker",
    "chink",
    "gook",
    "nip",
    "jap",
    "slant",
    "slanteye",
    "ching chong",
    "paki",
    "curry muncher",
    "sand nigger",
    "towelhead",
    "raghead",
    "camel jockey",
    "spic",
    "wetback",
    "beaner",
    "greaser",
    "spick",
    "kike",
    "heeb",
    "hymie",
    "zipperhead",
    "gypsy",
    "gyppo",
    "cracker",
    "honky",
    "redskin",
    "injun",
    "wagon burner",
    "prairie nigger",
    "abbo",
    "golliwog",
]
